// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/storage.go

// Package storage is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	storage "github.com/Sur0vy/cows_health.git/internal/storage"
	gomock "github.com/golang/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// AddFarm mocks base method.
func (m *MockStorage) AddFarm(с context.Context, farm storage.Farm) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFarm", с, farm)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFarm indicates an expected call of AddFarm.
func (mr *MockStorageMockRecorder) AddFarm(с, farm interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFarm", reflect.TypeOf((*MockStorage)(nil).AddFarm), с, farm)
}

// AddUser mocks base method.
func (m *MockStorage) AddUser(с context.Context, user storage.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", с, user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddUser indicates an expected call of AddUser.
func (mr *MockStorageMockRecorder) AddUser(с, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockStorage)(nil).AddUser), с, user)
}

// DelFarm mocks base method.
func (m *MockStorage) DelFarm(с context.Context, farmID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelFarm", с, farmID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelFarm indicates an expected call of DelFarm.
func (mr *MockStorageMockRecorder) DelFarm(с, farmID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelFarm", reflect.TypeOf((*MockStorage)(nil).DelFarm), с, farmID)
}

// GetFarms mocks base method.
func (m *MockStorage) GetFarms(с context.Context, userID int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFarms", с, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFarms indicates an expected call of GetFarms.
func (mr *MockStorageMockRecorder) GetFarms(с, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFarms", reflect.TypeOf((*MockStorage)(nil).GetFarms), с, userID)
}

// GetUser mocks base method.
func (m *MockStorage) GetUser(с context.Context, userHash string) *storage.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", с, userHash)
	ret0, _ := ret[0].(*storage.User)
	return ret0
}

// GetUser indicates an expected call of GetUser.
func (mr *MockStorageMockRecorder) GetUser(с, userHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockStorage)(nil).GetUser), с, userHash)
}

// GetUserHash mocks base method.
func (m *MockStorage) GetUserHash(с context.Context, user storage.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserHash", с, user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserHash indicates an expected call of GetUserHash.
func (mr *MockStorageMockRecorder) GetUserHash(с, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserHash", reflect.TypeOf((*MockStorage)(nil).GetUserHash), с, user)
}
